server:
  port: 8080

spring:
  application:
    name: greenway

  datasource:
#    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/${spring.application.name}
  # Windows
  # url: jdbc:h2:file:C:/data/sample/${spring.application.name}/db;
  #内存数据配置
  #spring.datasource.url=jdbc:h2:mem:testdb
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true